export const StaticUserData = {
  _id: '6491896c40c917addf58515a',
  name: 'Lospi Kyta',
  email: 'ys@yopmail.com',
  firstName: 'Lospi',
  lastName: 'Kyta',
  password: '$2a$10$IaIf2J8rS/va91YPtR0pluvShfC92laBeEaZaxVj2ccwbj9YECQSO',
  isEmailVerified: true,
  prefersClient: true,
  isClient: false,
  isTalentProfile: true,
  createdAt: '2023-03-29T09:39:11.450Z',
  __v: 0,
  expireToken: 0,
  resetToken: '',
  chatId: '...',
  userName: '...',
  profile_img: '...',
  lastActive: '...',
};
