export const GENERATE_INTERVIEW_QUESTION_PROMPT = `
Generate a set of interview questions for a candidate based on the provided extracted data. 
Group the questions into categories generated by AI, 
reflecting different aspects of the candidate's profile such as Introduction, 
and other categories based on the extracted data. 
Additionally, analyze the extracted data to determine an appropriate job title.
`;

export const GENERATE_INTERVIEW_QUESTION_INSTRUCTIONS = `
Instructions:
1. Formulate a total of 10 to 20 interview questions.
2. Group the questions into categories with a maximum of 4 questions per category.
3. Total categories should be a maximum of 4.
4. Aim for concise category names, preferably no more than two words each.
5. Use the information provided in the extractedData to generate relevant questions.
6. Utilize AI algorithms to generate categories based on the content of the extracted data.
7. Ensure a diverse set of questions across different categories.
8. Analyze the extracted data to determine an appropriate job title for the generated interview.
9. Ensure the array of categories is properly ordered
10. Format the output in the following array format:

{
  "jobTitle": //,
  "categories": [
    {
      "category": "Introduction", 
      "questions": [
        "Can you introduce yourself and provide a brief overview of your experience as a Python developer?", 
        "What motivated you to choose Python as your programming language?", 
        // ... (other questions in the Introduction category)
      ]
    },
    {
      "category": "Programming & Fundamentals", 
      "questions": [
        "Can you highlight and discuss the OOP concepts you know?", 
        "What is the difference between const and final?", 
        "How do you handle work under pressure?",
        // ... (other questions in the Programming & Fundamentals category)
      ]
    },
    // ... (other categories and questions)
  ]
}
`;

export const EXTRACT_JOB_TITLE_PROMPT = `
Analyze a dataset containing job details extracted to determine appropriate job titles. 
 Provide three different job titles that best match the analyzed data. 
 Format the output as an array of strings ["", "", ""]
`;

export const GENERATE_SUGGESTED_CATEGORIES_PROMPT = `
Generate 6 related words for the text:
`;

export const GENERATE_SUGGESTED_CATEGORIES_INSTRUCTIONS = `
Format the output as an array ["", "", ""].`


export const GENERATE_MORE_QUESTIONS_INSTRUCTIONS = `
Instructions:
1. Ensure the output is formatted as an array of strings like this: ["Question 1", "Question 2", "Question 3", "Question 4", "Question 5"].
2. Include commas between questions in the array.
3. Do not include numbering or additional formatting in the questions.
`;

